const DISCUSSIONS_FETCH_LOADING = "DISCUSSIONS_FETCH_LOADING";
const DISCUSSIONS_FETCH_SUCCESS = "DISCUSSIONS_FETCH_SUCCESS";
const DISCUSSIONS_PAGE_CHANGE = "DISCUSSIONS_PAGE_CHANGE";
const OTHERS_FETCH_SUCCESS = "OTHERS_FETCH_SUCCESS";
const OTHERS_PAGE_CHANGE = "OTHERS_PAGE_CHANGE";
const INIT_CHANGE = "INIT_CHANGE";
const MESSAGES_FETCH_LOADING = "MESSAGES_FETCH_LOADING";
const MESSAGES_FETCH_SUCCESS = "MESSAGES_FETCH_SUCCESS";
const NEW_MESSAGE = "NEW_MESSAGE";
const MESSAGE_SENT = "MESSAGE_SENT";

export {
  DISCUSSIONS_FETCH_LOADING,
  DISCUSSIONS_FETCH_SUCCESS,
  DISCUSSIONS_PAGE_CHANGE,
  OTHERS_FETCH_SUCCESS,
  OTHERS_PAGE_CHANGE,
  INIT_CHANGE,
  MESSAGES_FETCH_LOADING,
  MESSAGES_FETCH_SUCCESS,
  NEW_MESSAGE,
  MESSAGE_SENT
};
